### ISSUE TITLE
CLI - use yaml to configure sccs for service accounts instead of `oc adm  policy`

### ISSUE THREAD

**Issue by seansund** [ibm-garage-cloud/planning#300]

**Comment by seansund** [comment]
@csantanapr do you know the yaml equivalent for `oc adm policy add-scc-to-user privileged -z jenkins`?

**Comment by csantanapr** [comment]
Hi @seansund 

This commands what it does is add the service account/user "jenkins" in namespace "tools" to the resource object kind `scc` named `privileged`

The resource already exists, so what you need to do is "edit/patch" the resource and add a value to the array.

You can use the following command

```bash
oc patch scc privileged --type=json --patch '[{"path": "/users/-","op": "add","value": "system:serviceaccount:tools:jenkins"}]'
```

Final yaml would look like this
```yaml
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
  name: privileged
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
- system:cluster-admins
- system:nodes
- system:masters
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
- system:admin
- system:serviceaccount:openshift-infra:build-controller
- system:serviceaccount:tools:jenkins
volumes:
- '*'
```
