### ISSUE TITLE
Tekton Operator not installing on OCP 4.6

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/planning#612]
**Describe the bug**
Deploying the Toolkit on OCP 4.6 it doesn't install tekton

**To Reproduce**
1. Deploy OCP 4.6
2. Install the Toolkit

Results
Terraform waits for Tasks CRD and timeouts

**Comment by csantanapr** [comment]
RedHat release a new version of the operator `1.2.1`

The subscription now is different
```
  spec:
    channel: ocp-4.6
    installPlanApproval: Automatic
    name: openshift-pipelines-operator-rh
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: redhat-openshift-pipelines-operator.v1.2.1
```
