### ISSUE TITLE
Update actions to use 'latest' container images

### ISSUE THREAD

**Issue by lsteck** [ibm-garage-cloud/planning#713]
Should we update the github actions to always use the latest container image.  That way when we update an image we don't have to go to all the terraform modules git repos and update the version number in the action there.

For example in the [Terraform-tools-dashboard verify action](https://github.com/ibm-garage-cloud/terraform-tools-dashboard/blob/main/.github/workflows/verify.yaml) instead of this:
```
verify:
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip ci' ) }}
    runs-on: ubuntu-latest
    container: quay.io/ibmgaragecloud/cli-tools:v0.10.0-lite
```

It could be something like this
```
verify:
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip ci' ) }}
    runs-on: ubuntu-latest
    container: quay.io/ibmgaragecloud/cli-tools-lite:latest
```
